apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic-test
        image: 192.168.43.147:5000/tekton/petclinic-kaniko:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic-service
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - name: linilee-deploy
    nodePort: 12321
    port: 8080
    protocol: TCP
    targetPort: 8080
